version: "2.8"
services:
    website:
        build: .
        network_mode: bridge
        container_name: "website"
        expose:
            - "8000"
        command: bash start.sh
        restart: always
