version: '2.16'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=django-database
      - MYSQL_ROOT_PASSWORD=zmh200904
    ports:
      - "3306:3306"
    networks:
      - db_network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - db_network

  app:
    build:
      context: .
      dockerfile: Dockerfile-deploy
    ports:
      - "8000:8000"
    restart: always
    environment:
      - MYSQL=mysql
    command: bash -c "python manage.py migrate && gunicorn -c gunicorn.conf.py DjangoWebsite.wsgi:application"
    depends_on:
      - mysql
      - redis
    networks:
      - db_network
      - app_network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /compose/nginx/nginx.conf/:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app_network

networks:
  db_network:
    driver: bridge
  app_network:
    driver: bridge
